from PyQt5.QtWidgets import *


class CAdd_CHAN_GAO_Dialog(QDialog):
    def __init__(self, parent=None):
        super(CAdd_CHAN_GAO_Dialog, self).__init__(parent)

        self.label_CHAN_GAO_HAO = QLabel('产羔号(*)：')
        self.edit_CHAN_GAO_HAO = QLineEdit()
        self.layout_CHAN_GAO_HAO = QHBoxLayout()
        self.layout_CHAN_GAO_HAO.addWidget(self.label_CHAN_GAO_HAO)
        self.layout_CHAN_GAO_HAO.addWidget(self.edit_CHAN_GAO_HAO)

        self.label_PENG_HAO = QLabel('棚号(*)：')
        self.edit_PENG_HAO = QLineEdit()
        self.layout_PENG_HAO = QHBoxLayout()
        self.layout_PENG_HAO.addWidget(self.label_PENG_HAO)
        self.layout_PENG_HAO.addWidget(self.edit_PENG_HAO)

        self.label_LAN_HAO = QLabel('栏号(*)：')
        self.edit_LAN_HAO = QLineEdit()
        self.layout_LAN_HAO = QHBoxLayout()
        self.layout_LAN_HAO.addWidget(self.label_LAN_HAO)
        self.layout_LAN_HAO.addWidget(self.edit_LAN_HAO)

        self.label_MU_YANG_HAO = QLabel('母羊号(*)：')
        self.edit_MU_YANG_HAO = QLineEdit()
        self.layout_MU_YANG_HAO = QHBoxLayout()
        self.layout_MU_YANG_HAO.addWidget(self.label_MU_YANG_HAO)
        self.layout_MU_YANG_HAO.addWidget(self.edit_MU_YANG_HAO)

        self.label_GONG_YANG_HAO = QLabel('公羊号(*)：')
        self.edit_GONG_YANG_HAO = QLineEdit()
        self.layout_GONG_YANG_HAO = QHBoxLayout()
        self.layout_GONG_YANG_HAO.addWidget(self.label_GONG_YANG_HAO)
        self.layout_GONG_YANG_HAO.addWidget(self.edit_GONG_YANG_HAO)

        self.label_TAI_CI = QLabel('胎次：')
        self.edit_TAI_CI = QLineEdit()
        self.layout_TAI_CI = QHBoxLayout()
        self.layout_TAI_CI.addWidget(self.label_TAI_CI)
        self.layout_TAI_CI.addWidget(self.edit_TAI_CI)

        self.label_PEI_ZHONG_RI_QI = QLabel('配种日期：')
        self.edit_PEI_ZHONG_RI_QI_year = QLineEdit()
        self.label_PEI_ZHONG_RI_QI_year = QLabel('年')
        self.edit_PEI_ZHONG_RI_QI_month = QLineEdit()
        self.label_PEI_ZHONG_RI_QI_month = QLabel('月')
        self.edit_PEI_ZHONG_RI_QI_day = QLineEdit()
        self.label_PEI_ZHONG_RI_QI_day = QLabel('日')
        self.layout_PEI_ZHONG_RI_QI = QHBoxLayout()
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.label_PEI_ZHONG_RI_QI)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.edit_PEI_ZHONG_RI_QI_year)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.label_PEI_ZHONG_RI_QI_year)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.edit_PEI_ZHONG_RI_QI_month)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.label_PEI_ZHONG_RI_QI_month)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.edit_PEI_ZHONG_RI_QI_day)
        self.layout_PEI_ZHONG_RI_QI.addWidget(self.label_PEI_ZHONG_RI_QI_day)

        self.label_CHAN_GAO_RI_QI = QLabel('产羔日期(*)：')
        self.edit_CHAN_GAO_RI_QI_year = QLineEdit()
        self.label_CHAN_GAO_RI_QI_year = QLabel('年')
        self.edit_CHAN_GAO_RI_QI_month = QLineEdit()
        self.label_CHAN_GAO_RI_QI_month = QLabel('月')
        self.edit_CHAN_GAO_RI_QI_day = QLineEdit()
        self.label_CHAN_GAO_RI_QI_day = QLabel('日')
        self.layout_CHAN_GAO_RI_QI = QHBoxLayout()
        self.layout_CHAN_GAO_RI_QI.addWidget(self.label_CHAN_GAO_RI_QI)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.edit_CHAN_GAO_RI_QI_year)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.label_CHAN_GAO_RI_QI_year)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.edit_CHAN_GAO_RI_QI_month)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.label_CHAN_GAO_RI_QI_month)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.edit_CHAN_GAO_RI_QI_day)
        self.layout_CHAN_GAO_RI_QI.addWidget(self.label_CHAN_GAO_RI_QI_day)

        self.label_CHAN_GAO = QLabel('产羔数(*)：')
        self.edit_CHAN_GAO = QLineEdit()
        self.layout_CHAN_GAO = QHBoxLayout()
        self.layout_CHAN_GAO.addWidget(self.label_CHAN_GAO)
        self.layout_CHAN_GAO.addWidget(self.edit_CHAN_GAO)
        
        self.label_HUO_GAO=QLabel('活羔(*)：')
        self.edit_HUO_GAO=QLineEdit()
        self.layout_HUO_GAO=QHBoxLayout()
        self.layout_HUO_GAO.addWidget(self.label_HUO_GAO)
        self.layout_HUO_GAO.addWidget(self.edit_HUO_GAO)
        
        self.label_DUAN_NAI_RI_QI = QLabel('断奶日期：')
        self.edit_DUAN_NAI_RI_QI_year = QLineEdit()
        self.label_DUAN_NAI_RI_QI_year = QLabel('年')
        self.edit_DUAN_NAI_RI_QI_month = QLineEdit()
        self.label_DUAN_NAI_RI_QI_month = QLabel('月')
        self.edit_DUAN_NAI_RI_QI_day = QLineEdit()
        self.label_DUAN_NAI_RI_QI_day = QLabel('日')
        self.layout_DUAN_NAI_RI_QI = QHBoxLayout()
        self.layout_DUAN_NAI_RI_QI.addWidget(self.label_DUAN_NAI_RI_QI)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.edit_DUAN_NAI_RI_QI_year)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.label_DUAN_NAI_RI_QI_year)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.edit_DUAN_NAI_RI_QI_month)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.label_DUAN_NAI_RI_QI_month)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.edit_DUAN_NAI_RI_QI_day)
        self.layout_DUAN_NAI_RI_QI.addWidget(self.label_DUAN_NAI_RI_QI_day)
        
        self.button_add_CHAN_GAO_dialog=QPushButton('添加产羔信息')

        self.layout_add_CHAN_GAO_dialog = QVBoxLayout()
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_CHAN_GAO_HAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_PENG_HAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_LAN_HAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_MU_YANG_HAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_GONG_YANG_HAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_TAI_CI)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_PEI_ZHONG_RI_QI)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_CHAN_GAO_RI_QI)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_CHAN_GAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_HUO_GAO)
        self.layout_add_CHAN_GAO_dialog.addLayout(self.layout_DUAN_NAI_RI_QI)
        self.layout_add_CHAN_GAO_dialog.addWidget(self.button_add_CHAN_GAO_dialog)

        self.setLayout(self.layout_add_CHAN_GAO_dialog)